#!/bin/sh
echo "script executed" >> ~/.xfcelogging
if [ `xrandr -q | grep '^DP1 connected' | wc -l` -ne 0 ]
then
    echo "Setting up external screen as primary display and scaling to sane size"
    xrandr --dpi 186 --output DP1 --primary --scale 2x2 --mode 1920x1080 --pos 0x0 --output eDP1 --pos 3840x0
    echo "external monitor setup" >> ~/.xfcelogging
else
    echo "No external screen to configure"
fi
